# Generated by Django 2.1.3 on 2018-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.FileField(upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
